services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jwt_security
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-security-network
  backend:
    container_name: backend
    image: spring-boot-3-jwt-security
    ports:
      - "8080:8080"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-security-network
    depends_on:
      - postgres


volumes:
  postgres:

networks:
  spring-security-network:
    driver: bridge